export const industryList = [
    "Medical Clinics",
    "Dentists",
    "Psychologists",
    "Physiologist",
    "Acupuncure",
    "Chiropractor",
    "Physical Therapists",
    "Prosthectics and Orthotics",
    "Coaching",
    "Charity",
    "Professional Services",
    "Government and Public Sector",
    "Fitness and Sports",
    "Beauty, Hair and Nair Salons",
    "Barber",
    "Spa",
    "Personal Trainers",
    "Design Constations",
    "Counselling",
    "Cleaning Services",
    "Religious Consultations",
    "Interview Scheduling",
    "Financial Services",
    "Business Advisory",
    "Legal Services",
    "City Councils",
    "Equipment Rentals",
    "Restuarants",
    "Tutoring services",
    "Education and Non-Profits",
  ];
  