import { Metadata } from "next";
import { montserrat } from "../utils/fonts";

export const metadata: Metadata = {
  title: "Zikoro Bookings",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className={`${montserrat.className}`}> {children}</main>
      </body>
    </html>
  );
}
